services:
  db:
    image: postgres:16-alpine
    container_name: odoo18-db-informatica
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - odoo18-db-informatica-data:/var/lib/postgresql/data
    restart: unless-stopped

  odoo:
    image: odoo:18.0
    container_name: odoo18-informatica
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8072:8072"
    environment:
      HOST: db
      USER: ${POSTGRES_USER}
      PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - odoo18-web-informatica-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
    restart: unless-stopped

volumes:
  odoo18-db-informatica-data:
  odoo18-web-informatica-data: